/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkOrdersRouteImport } from './routes/work-orders'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as StepTemplatesRouteImport } from './routes/step-templates'
import { Route as StationsRouteImport } from './routes/stations'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as MasterDataRouteImport } from './routes/master-data'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LinesRouteImport } from './routes/lines'
import { Route as GenealogyRouteImport } from './routes/genealogy'
import { Route as ExecutionRouteImport } from './routes/execution'
import { Route as DowntimeRouteImport } from './routes/downtime'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkOrdersWoIdRouteImport } from './routes/work-orders.$woId'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as StationsStationIdRouteImport } from './routes/stations.$stationId'
import { Route as LinesLineIdRouteImport } from './routes/lines.$lineId'

const WorkOrdersRoute = WorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const StepTemplatesRoute = StepTemplatesRouteImport.update({
  id: '/step-templates',
  path: '/step-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsRoute = StationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataRoute = MasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LinesRoute = LinesRouteImport.update({
  id: '/lines',
  path: '/lines',
  getParentRoute: () => rootRouteImport,
} as any)
const GenealogyRoute = GenealogyRouteImport.update({
  id: '/genealogy',
  path: '/genealogy',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionRoute = ExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => rootRouteImport,
} as any)
const DowntimeRoute = DowntimeRouteImport.update({
  id: '/downtime',
  path: '/downtime',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrdersWoIdRoute = WorkOrdersWoIdRouteImport.update({
  id: '/$woId',
  path: '/$woId',
  getParentRoute: () => WorkOrdersRoute,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRoute,
} as any)
const StationsStationIdRoute = StationsStationIdRouteImport.update({
  id: '/$stationId',
  path: '/$stationId',
  getParentRoute: () => StationsRoute,
} as any)
const LinesLineIdRoute = LinesLineIdRouteImport.update({
  id: '/$lineId',
  path: '/$lineId',
  getParentRoute: () => LinesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/audit': typeof AuditRoute
  '/downtime': typeof DowntimeRoute
  '/execution': typeof ExecutionRoute
  '/genealogy': typeof GenealogyRoute
  '/lines': typeof LinesRouteWithChildren
  '/live': typeof LiveRoute
  '/master-data': typeof MasterDataRoute
  '/quality': typeof QualityRoute
  '/settings': typeof SettingsRoute
  '/stations': typeof StationsRouteWithChildren
  '/step-templates': typeof StepTemplatesRoute
  '/telemetry': typeof TelemetryRoute
  '/users': typeof UsersRouteWithChildren
  '/work-orders': typeof WorkOrdersRouteWithChildren
  '/lines/$lineId': typeof LinesLineIdRoute
  '/stations/$stationId': typeof StationsStationIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/work-orders/$woId': typeof WorkOrdersWoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/audit': typeof AuditRoute
  '/downtime': typeof DowntimeRoute
  '/execution': typeof ExecutionRoute
  '/genealogy': typeof GenealogyRoute
  '/lines': typeof LinesRouteWithChildren
  '/live': typeof LiveRoute
  '/master-data': typeof MasterDataRoute
  '/quality': typeof QualityRoute
  '/settings': typeof SettingsRoute
  '/stations': typeof StationsRouteWithChildren
  '/step-templates': typeof StepTemplatesRoute
  '/telemetry': typeof TelemetryRoute
  '/users': typeof UsersRouteWithChildren
  '/work-orders': typeof WorkOrdersRouteWithChildren
  '/lines/$lineId': typeof LinesLineIdRoute
  '/stations/$stationId': typeof StationsStationIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/work-orders/$woId': typeof WorkOrdersWoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/audit': typeof AuditRoute
  '/downtime': typeof DowntimeRoute
  '/execution': typeof ExecutionRoute
  '/genealogy': typeof GenealogyRoute
  '/lines': typeof LinesRouteWithChildren
  '/live': typeof LiveRoute
  '/master-data': typeof MasterDataRoute
  '/quality': typeof QualityRoute
  '/settings': typeof SettingsRoute
  '/stations': typeof StationsRouteWithChildren
  '/step-templates': typeof StepTemplatesRoute
  '/telemetry': typeof TelemetryRoute
  '/users': typeof UsersRouteWithChildren
  '/work-orders': typeof WorkOrdersRouteWithChildren
  '/lines/$lineId': typeof LinesLineIdRoute
  '/stations/$stationId': typeof StationsStationIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/work-orders/$woId': typeof WorkOrdersWoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/audit'
    | '/downtime'
    | '/execution'
    | '/genealogy'
    | '/lines'
    | '/live'
    | '/master-data'
    | '/quality'
    | '/settings'
    | '/stations'
    | '/step-templates'
    | '/telemetry'
    | '/users'
    | '/work-orders'
    | '/lines/$lineId'
    | '/stations/$stationId'
    | '/users/$userId'
    | '/work-orders/$woId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments'
    | '/audit'
    | '/downtime'
    | '/execution'
    | '/genealogy'
    | '/lines'
    | '/live'
    | '/master-data'
    | '/quality'
    | '/settings'
    | '/stations'
    | '/step-templates'
    | '/telemetry'
    | '/users'
    | '/work-orders'
    | '/lines/$lineId'
    | '/stations/$stationId'
    | '/users/$userId'
    | '/work-orders/$woId'
  id:
    | '__root__'
    | '/'
    | '/assignments'
    | '/audit'
    | '/downtime'
    | '/execution'
    | '/genealogy'
    | '/lines'
    | '/live'
    | '/master-data'
    | '/quality'
    | '/settings'
    | '/stations'
    | '/step-templates'
    | '/telemetry'
    | '/users'
    | '/work-orders'
    | '/lines/$lineId'
    | '/stations/$stationId'
    | '/users/$userId'
    | '/work-orders/$woId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRoute
  AuditRoute: typeof AuditRoute
  DowntimeRoute: typeof DowntimeRoute
  ExecutionRoute: typeof ExecutionRoute
  GenealogyRoute: typeof GenealogyRoute
  LinesRoute: typeof LinesRouteWithChildren
  LiveRoute: typeof LiveRoute
  MasterDataRoute: typeof MasterDataRoute
  QualityRoute: typeof QualityRoute
  SettingsRoute: typeof SettingsRoute
  StationsRoute: typeof StationsRouteWithChildren
  StepTemplatesRoute: typeof StepTemplatesRoute
  TelemetryRoute: typeof TelemetryRoute
  UsersRoute: typeof UsersRouteWithChildren
  WorkOrdersRoute: typeof WorkOrdersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-orders': {
      id: '/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof WorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/step-templates': {
      id: '/step-templates'
      path: '/step-templates'
      fullPath: '/step-templates'
      preLoaderRoute: typeof StepTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations': {
      id: '/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data': {
      id: '/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof MasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lines': {
      id: '/lines'
      path: '/lines'
      fullPath: '/lines'
      preLoaderRoute: typeof LinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genealogy': {
      id: '/genealogy'
      path: '/genealogy'
      fullPath: '/genealogy'
      preLoaderRoute: typeof GenealogyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execution': {
      id: '/execution'
      path: '/execution'
      fullPath: '/execution'
      preLoaderRoute: typeof ExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downtime': {
      id: '/downtime'
      path: '/downtime'
      fullPath: '/downtime'
      preLoaderRoute: typeof DowntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-orders/$woId': {
      id: '/work-orders/$woId'
      path: '/$woId'
      fullPath: '/work-orders/$woId'
      preLoaderRoute: typeof WorkOrdersWoIdRouteImport
      parentRoute: typeof WorkOrdersRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRoute
    }
    '/stations/$stationId': {
      id: '/stations/$stationId'
      path: '/$stationId'
      fullPath: '/stations/$stationId'
      preLoaderRoute: typeof StationsStationIdRouteImport
      parentRoute: typeof StationsRoute
    }
    '/lines/$lineId': {
      id: '/lines/$lineId'
      path: '/$lineId'
      fullPath: '/lines/$lineId'
      preLoaderRoute: typeof LinesLineIdRouteImport
      parentRoute: typeof LinesRoute
    }
  }
}

interface LinesRouteChildren {
  LinesLineIdRoute: typeof LinesLineIdRoute
}

const LinesRouteChildren: LinesRouteChildren = {
  LinesLineIdRoute: LinesLineIdRoute,
}

const LinesRouteWithChildren = LinesRoute._addFileChildren(LinesRouteChildren)

interface StationsRouteChildren {
  StationsStationIdRoute: typeof StationsStationIdRoute
}

const StationsRouteChildren: StationsRouteChildren = {
  StationsStationIdRoute: StationsStationIdRoute,
}

const StationsRouteWithChildren = StationsRoute._addFileChildren(
  StationsRouteChildren,
)

interface UsersRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersUserIdRoute: UsersUserIdRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

interface WorkOrdersRouteChildren {
  WorkOrdersWoIdRoute: typeof WorkOrdersWoIdRoute
}

const WorkOrdersRouteChildren: WorkOrdersRouteChildren = {
  WorkOrdersWoIdRoute: WorkOrdersWoIdRoute,
}

const WorkOrdersRouteWithChildren = WorkOrdersRoute._addFileChildren(
  WorkOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRoute,
  AuditRoute: AuditRoute,
  DowntimeRoute: DowntimeRoute,
  ExecutionRoute: ExecutionRoute,
  GenealogyRoute: GenealogyRoute,
  LinesRoute: LinesRouteWithChildren,
  LiveRoute: LiveRoute,
  MasterDataRoute: MasterDataRoute,
  QualityRoute: QualityRoute,
  SettingsRoute: SettingsRoute,
  StationsRoute: StationsRouteWithChildren,
  StepTemplatesRoute: StepTemplatesRoute,
  TelemetryRoute: TelemetryRoute,
  UsersRoute: UsersRouteWithChildren,
  WorkOrdersRoute: WorkOrdersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
