/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWasteReasonsRouteImport } from './routes/_authenticated/waste-reasons'
import { Route as AuthenticatedTrackingRouteImport } from './routes/_authenticated/tracking'
import { Route as AuthenticatedTraceabilityRouteImport } from './routes/_authenticated/traceability'
import { Route as AuthenticatedTelemetryRouteImport } from './routes/_authenticated/telemetry'
import { Route as AuthenticatedStepTemplatesRouteImport } from './routes/_authenticated/step-templates'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRecipesRouteImport } from './routes/_authenticated/recipes'
import { Route as AuthenticatedQualityRouteImport } from './routes/_authenticated/quality'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedMasterDataRouteImport } from './routes/_authenticated/master-data'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedGenealogyRouteImport } from './routes/_authenticated/genealogy'
import { Route as AuthenticatedExecutionRouteImport } from './routes/_authenticated/execution'
import { Route as AuthenticatedDowntimeRouteImport } from './routes/_authenticated/downtime'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedWorkOrdersIndexRouteImport } from './routes/_authenticated/work-orders.index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users.index'
import { Route as AuthenticatedStationsIndexRouteImport } from './routes/_authenticated/stations.index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products.index'
import { Route as AuthenticatedProductionOrdersIndexRouteImport } from './routes/_authenticated/production-orders.index'
import { Route as AuthenticatedOperatorIndexRouteImport } from './routes/_authenticated/operator.index'
import { Route as AuthenticatedLinesIndexRouteImport } from './routes/_authenticated/lines.index'
import { Route as AuthenticatedHmiIndexRouteImport } from './routes/_authenticated/hmi.index'
import { Route as AuthenticatedWorkOrdersWoIdRouteImport } from './routes/_authenticated/work-orders.$woId'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users.$userId'
import { Route as AuthenticatedUnitsUidRouteImport } from './routes/_authenticated/units.$uid'
import { Route as AuthenticatedStationsStationIdRouteImport } from './routes/_authenticated/stations.$stationId'
import { Route as AuthenticatedProductsProductIdRouteImport } from './routes/_authenticated/products.$productId'
import { Route as AuthenticatedProductionOrdersPoIdRouteImport } from './routes/_authenticated/production-orders.$poId'
import { Route as AuthenticatedOperatorStationIdRouteImport } from './routes/_authenticated/operator.$stationId'
import { Route as AuthenticatedLinesLineIdRouteImport } from './routes/_authenticated/lines.$lineId'
import { Route as AuthenticatedHmiStationIdRouteImport } from './routes/_authenticated/hmi.$stationId'
import { Route as AuthenticatedBatchesBatchIdRouteImport } from './routes/_authenticated/batches.$batchId'
import { Route as ApiPublicMesWorkOrdersRouteImport } from './routes/api/public/mes/work-orders'
import { Route as ApiPublicMesTraceabilityRouteImport } from './routes/api/public/mes/traceability'
import { Route as ApiPublicMesQualityHoldsRouteImport } from './routes/api/public/mes/quality-holds'
import { Route as ApiPublicMesKpiRouteImport } from './routes/api/public/mes/kpi'
import { Route as ApiPublicMesDowntimeRouteImport } from './routes/api/public/mes/downtime'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWasteReasonsRoute =
  AuthenticatedWasteReasonsRouteImport.update({
    id: '/_authenticated/waste-reasons',
    path: '/waste-reasons',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTrackingRoute = AuthenticatedTrackingRouteImport.update({
  id: '/_authenticated/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTraceabilityRoute =
  AuthenticatedTraceabilityRouteImport.update({
    id: '/_authenticated/traceability',
    path: '/traceability',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTelemetryRoute = AuthenticatedTelemetryRouteImport.update({
  id: '/_authenticated/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStepTemplatesRoute =
  AuthenticatedStepTemplatesRouteImport.update({
    id: '/_authenticated/step-templates',
    path: '/step-templates',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/_authenticated/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecipesRoute = AuthenticatedRecipesRouteImport.update({
  id: '/_authenticated/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQualityRoute = AuthenticatedQualityRouteImport.update({
  id: '/_authenticated/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/_authenticated/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMasterDataRoute = AuthenticatedMasterDataRouteImport.update({
  id: '/_authenticated/master-data',
  path: '/master-data',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/_authenticated/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGenealogyRoute = AuthenticatedGenealogyRouteImport.update({
  id: '/_authenticated/genealogy',
  path: '/genealogy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExecutionRoute = AuthenticatedExecutionRouteImport.update({
  id: '/_authenticated/execution',
  path: '/execution',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDowntimeRoute = AuthenticatedDowntimeRouteImport.update({
  id: '/_authenticated/downtime',
  path: '/downtime',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/_authenticated/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/_authenticated/assignments',
    path: '/assignments',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedWorkOrdersIndexRoute =
  AuthenticatedWorkOrdersIndexRouteImport.update({
    id: '/_authenticated/work-orders/',
    path: '/work-orders/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/_authenticated/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStationsIndexRoute =
  AuthenticatedStationsIndexRouteImport.update({
    id: '/_authenticated/stations/',
    path: '/stations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/_authenticated/products/',
    path: '/products/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProductionOrdersIndexRoute =
  AuthenticatedProductionOrdersIndexRouteImport.update({
    id: '/_authenticated/production-orders/',
    path: '/production-orders/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOperatorIndexRoute =
  AuthenticatedOperatorIndexRouteImport.update({
    id: '/_authenticated/operator/',
    path: '/operator/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedLinesIndexRoute = AuthenticatedLinesIndexRouteImport.update({
  id: '/_authenticated/lines/',
  path: '/lines/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHmiIndexRoute = AuthenticatedHmiIndexRouteImport.update({
  id: '/_authenticated/hmi/',
  path: '/hmi/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkOrdersWoIdRoute =
  AuthenticatedWorkOrdersWoIdRouteImport.update({
    id: '/_authenticated/work-orders/$woId',
    path: '/work-orders/$woId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/_authenticated/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedUnitsUidRoute = AuthenticatedUnitsUidRouteImport.update({
  id: '/_authenticated/units/$uid',
  path: '/units/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStationsStationIdRoute =
  AuthenticatedStationsStationIdRouteImport.update({
    id: '/_authenticated/stations/$stationId',
    path: '/stations/$stationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProductsProductIdRoute =
  AuthenticatedProductsProductIdRouteImport.update({
    id: '/_authenticated/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProductionOrdersPoIdRoute =
  AuthenticatedProductionOrdersPoIdRouteImport.update({
    id: '/_authenticated/production-orders/$poId',
    path: '/production-orders/$poId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOperatorStationIdRoute =
  AuthenticatedOperatorStationIdRouteImport.update({
    id: '/_authenticated/operator/$stationId',
    path: '/operator/$stationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedLinesLineIdRoute =
  AuthenticatedLinesLineIdRouteImport.update({
    id: '/_authenticated/lines/$lineId',
    path: '/lines/$lineId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedHmiStationIdRoute =
  AuthenticatedHmiStationIdRouteImport.update({
    id: '/_authenticated/hmi/$stationId',
    path: '/hmi/$stationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBatchesBatchIdRoute =
  AuthenticatedBatchesBatchIdRouteImport.update({
    id: '/_authenticated/batches/$batchId',
    path: '/batches/$batchId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMesWorkOrdersRoute = ApiPublicMesWorkOrdersRouteImport.update({
  id: '/api/public/mes/work-orders',
  path: '/api/public/mes/work-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMesTraceabilityRoute =
  ApiPublicMesTraceabilityRouteImport.update({
    id: '/api/public/mes/traceability',
    path: '/api/public/mes/traceability',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMesQualityHoldsRoute =
  ApiPublicMesQualityHoldsRouteImport.update({
    id: '/api/public/mes/quality-holds',
    path: '/api/public/mes/quality-holds',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMesKpiRoute = ApiPublicMesKpiRouteImport.update({
  id: '/api/public/mes/kpi',
  path: '/api/public/mes/kpi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMesDowntimeRoute = ApiPublicMesDowntimeRouteImport.update({
  id: '/api/public/mes/downtime',
  path: '/api/public/mes/downtime',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/downtime': typeof AuthenticatedDowntimeRoute
  '/execution': typeof AuthenticatedExecutionRoute
  '/genealogy': typeof AuthenticatedGenealogyRoute
  '/live': typeof AuthenticatedLiveRoute
  '/master-data': typeof AuthenticatedMasterDataRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/step-templates': typeof AuthenticatedStepTemplatesRoute
  '/telemetry': typeof AuthenticatedTelemetryRoute
  '/traceability': typeof AuthenticatedTraceabilityRoute
  '/tracking': typeof AuthenticatedTrackingRoute
  '/waste-reasons': typeof AuthenticatedWasteReasonsRoute
  '/': typeof AuthenticatedIndexRoute
  '/batches/$batchId': typeof AuthenticatedBatchesBatchIdRoute
  '/hmi/$stationId': typeof AuthenticatedHmiStationIdRoute
  '/lines/$lineId': typeof AuthenticatedLinesLineIdRoute
  '/operator/$stationId': typeof AuthenticatedOperatorStationIdRoute
  '/production-orders/$poId': typeof AuthenticatedProductionOrdersPoIdRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/stations/$stationId': typeof AuthenticatedStationsStationIdRoute
  '/units/$uid': typeof AuthenticatedUnitsUidRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/work-orders/$woId': typeof AuthenticatedWorkOrdersWoIdRoute
  '/hmi/': typeof AuthenticatedHmiIndexRoute
  '/lines/': typeof AuthenticatedLinesIndexRoute
  '/operator/': typeof AuthenticatedOperatorIndexRoute
  '/production-orders/': typeof AuthenticatedProductionOrdersIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/stations/': typeof AuthenticatedStationsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/work-orders/': typeof AuthenticatedWorkOrdersIndexRoute
  '/api/public/mes/downtime': typeof ApiPublicMesDowntimeRoute
  '/api/public/mes/kpi': typeof ApiPublicMesKpiRoute
  '/api/public/mes/quality-holds': typeof ApiPublicMesQualityHoldsRoute
  '/api/public/mes/traceability': typeof ApiPublicMesTraceabilityRoute
  '/api/public/mes/work-orders': typeof ApiPublicMesWorkOrdersRoute
}
export interface FileRoutesByTo {
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/downtime': typeof AuthenticatedDowntimeRoute
  '/execution': typeof AuthenticatedExecutionRoute
  '/genealogy': typeof AuthenticatedGenealogyRoute
  '/live': typeof AuthenticatedLiveRoute
  '/master-data': typeof AuthenticatedMasterDataRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/step-templates': typeof AuthenticatedStepTemplatesRoute
  '/telemetry': typeof AuthenticatedTelemetryRoute
  '/traceability': typeof AuthenticatedTraceabilityRoute
  '/tracking': typeof AuthenticatedTrackingRoute
  '/waste-reasons': typeof AuthenticatedWasteReasonsRoute
  '/': typeof AuthenticatedIndexRoute
  '/batches/$batchId': typeof AuthenticatedBatchesBatchIdRoute
  '/hmi/$stationId': typeof AuthenticatedHmiStationIdRoute
  '/lines/$lineId': typeof AuthenticatedLinesLineIdRoute
  '/operator/$stationId': typeof AuthenticatedOperatorStationIdRoute
  '/production-orders/$poId': typeof AuthenticatedProductionOrdersPoIdRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/stations/$stationId': typeof AuthenticatedStationsStationIdRoute
  '/units/$uid': typeof AuthenticatedUnitsUidRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/work-orders/$woId': typeof AuthenticatedWorkOrdersWoIdRoute
  '/hmi': typeof AuthenticatedHmiIndexRoute
  '/lines': typeof AuthenticatedLinesIndexRoute
  '/operator': typeof AuthenticatedOperatorIndexRoute
  '/production-orders': typeof AuthenticatedProductionOrdersIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/stations': typeof AuthenticatedStationsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/work-orders': typeof AuthenticatedWorkOrdersIndexRoute
  '/api/public/mes/downtime': typeof ApiPublicMesDowntimeRoute
  '/api/public/mes/kpi': typeof ApiPublicMesKpiRoute
  '/api/public/mes/quality-holds': typeof ApiPublicMesQualityHoldsRoute
  '/api/public/mes/traceability': typeof ApiPublicMesTraceabilityRoute
  '/api/public/mes/work-orders': typeof ApiPublicMesWorkOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/downtime': typeof AuthenticatedDowntimeRoute
  '/_authenticated/execution': typeof AuthenticatedExecutionRoute
  '/_authenticated/genealogy': typeof AuthenticatedGenealogyRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/master-data': typeof AuthenticatedMasterDataRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/quality': typeof AuthenticatedQualityRoute
  '/_authenticated/recipes': typeof AuthenticatedRecipesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/step-templates': typeof AuthenticatedStepTemplatesRoute
  '/_authenticated/telemetry': typeof AuthenticatedTelemetryRoute
  '/_authenticated/traceability': typeof AuthenticatedTraceabilityRoute
  '/_authenticated/tracking': typeof AuthenticatedTrackingRoute
  '/_authenticated/waste-reasons': typeof AuthenticatedWasteReasonsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/batches/$batchId': typeof AuthenticatedBatchesBatchIdRoute
  '/_authenticated/hmi/$stationId': typeof AuthenticatedHmiStationIdRoute
  '/_authenticated/lines/$lineId': typeof AuthenticatedLinesLineIdRoute
  '/_authenticated/operator/$stationId': typeof AuthenticatedOperatorStationIdRoute
  '/_authenticated/production-orders/$poId': typeof AuthenticatedProductionOrdersPoIdRoute
  '/_authenticated/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/_authenticated/stations/$stationId': typeof AuthenticatedStationsStationIdRoute
  '/_authenticated/units/$uid': typeof AuthenticatedUnitsUidRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/_authenticated/work-orders/$woId': typeof AuthenticatedWorkOrdersWoIdRoute
  '/_authenticated/hmi/': typeof AuthenticatedHmiIndexRoute
  '/_authenticated/lines/': typeof AuthenticatedLinesIndexRoute
  '/_authenticated/operator/': typeof AuthenticatedOperatorIndexRoute
  '/_authenticated/production-orders/': typeof AuthenticatedProductionOrdersIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/stations/': typeof AuthenticatedStationsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/work-orders/': typeof AuthenticatedWorkOrdersIndexRoute
  '/api/public/mes/downtime': typeof ApiPublicMesDowntimeRoute
  '/api/public/mes/kpi': typeof ApiPublicMesKpiRoute
  '/api/public/mes/quality-holds': typeof ApiPublicMesQualityHoldsRoute
  '/api/public/mes/traceability': typeof ApiPublicMesTraceabilityRoute
  '/api/public/mes/work-orders': typeof ApiPublicMesWorkOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/assignments'
    | '/audit'
    | '/downtime'
    | '/execution'
    | '/genealogy'
    | '/live'
    | '/master-data'
    | '/planner'
    | '/quality'
    | '/recipes'
    | '/settings'
    | '/step-templates'
    | '/telemetry'
    | '/traceability'
    | '/tracking'
    | '/waste-reasons'
    | '/'
    | '/batches/$batchId'
    | '/hmi/$stationId'
    | '/lines/$lineId'
    | '/operator/$stationId'
    | '/production-orders/$poId'
    | '/products/$productId'
    | '/stations/$stationId'
    | '/units/$uid'
    | '/users/$userId'
    | '/work-orders/$woId'
    | '/hmi/'
    | '/lines/'
    | '/operator/'
    | '/production-orders/'
    | '/products/'
    | '/stations/'
    | '/users/'
    | '/work-orders/'
    | '/api/public/mes/downtime'
    | '/api/public/mes/kpi'
    | '/api/public/mes/quality-holds'
    | '/api/public/mes/traceability'
    | '/api/public/mes/work-orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/assignments'
    | '/audit'
    | '/downtime'
    | '/execution'
    | '/genealogy'
    | '/live'
    | '/master-data'
    | '/planner'
    | '/quality'
    | '/recipes'
    | '/settings'
    | '/step-templates'
    | '/telemetry'
    | '/traceability'
    | '/tracking'
    | '/waste-reasons'
    | '/'
    | '/batches/$batchId'
    | '/hmi/$stationId'
    | '/lines/$lineId'
    | '/operator/$stationId'
    | '/production-orders/$poId'
    | '/products/$productId'
    | '/stations/$stationId'
    | '/units/$uid'
    | '/users/$userId'
    | '/work-orders/$woId'
    | '/hmi'
    | '/lines'
    | '/operator'
    | '/production-orders'
    | '/products'
    | '/stations'
    | '/users'
    | '/work-orders'
    | '/api/public/mes/downtime'
    | '/api/public/mes/kpi'
    | '/api/public/mes/quality-holds'
    | '/api/public/mes/traceability'
    | '/api/public/mes/work-orders'
  id:
    | '__root__'
    | '/_authenticated/assignments'
    | '/_authenticated/audit'
    | '/_authenticated/downtime'
    | '/_authenticated/execution'
    | '/_authenticated/genealogy'
    | '/_authenticated/live'
    | '/_authenticated/master-data'
    | '/_authenticated/planner'
    | '/_authenticated/quality'
    | '/_authenticated/recipes'
    | '/_authenticated/settings'
    | '/_authenticated/step-templates'
    | '/_authenticated/telemetry'
    | '/_authenticated/traceability'
    | '/_authenticated/tracking'
    | '/_authenticated/waste-reasons'
    | '/_authenticated/'
    | '/_authenticated/batches/$batchId'
    | '/_authenticated/hmi/$stationId'
    | '/_authenticated/lines/$lineId'
    | '/_authenticated/operator/$stationId'
    | '/_authenticated/production-orders/$poId'
    | '/_authenticated/products/$productId'
    | '/_authenticated/stations/$stationId'
    | '/_authenticated/units/$uid'
    | '/_authenticated/users/$userId'
    | '/_authenticated/work-orders/$woId'
    | '/_authenticated/hmi/'
    | '/_authenticated/lines/'
    | '/_authenticated/operator/'
    | '/_authenticated/production-orders/'
    | '/_authenticated/products/'
    | '/_authenticated/stations/'
    | '/_authenticated/users/'
    | '/_authenticated/work-orders/'
    | '/api/public/mes/downtime'
    | '/api/public/mes/kpi'
    | '/api/public/mes/quality-holds'
    | '/api/public/mes/traceability'
    | '/api/public/mes/work-orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDowntimeRoute: typeof AuthenticatedDowntimeRoute
  AuthenticatedExecutionRoute: typeof AuthenticatedExecutionRoute
  AuthenticatedGenealogyRoute: typeof AuthenticatedGenealogyRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedMasterDataRoute: typeof AuthenticatedMasterDataRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedQualityRoute: typeof AuthenticatedQualityRoute
  AuthenticatedRecipesRoute: typeof AuthenticatedRecipesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStepTemplatesRoute: typeof AuthenticatedStepTemplatesRoute
  AuthenticatedTelemetryRoute: typeof AuthenticatedTelemetryRoute
  AuthenticatedTraceabilityRoute: typeof AuthenticatedTraceabilityRoute
  AuthenticatedTrackingRoute: typeof AuthenticatedTrackingRoute
  AuthenticatedWasteReasonsRoute: typeof AuthenticatedWasteReasonsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBatchesBatchIdRoute: typeof AuthenticatedBatchesBatchIdRoute
  AuthenticatedHmiStationIdRoute: typeof AuthenticatedHmiStationIdRoute
  AuthenticatedLinesLineIdRoute: typeof AuthenticatedLinesLineIdRoute
  AuthenticatedOperatorStationIdRoute: typeof AuthenticatedOperatorStationIdRoute
  AuthenticatedProductionOrdersPoIdRoute: typeof AuthenticatedProductionOrdersPoIdRoute
  AuthenticatedProductsProductIdRoute: typeof AuthenticatedProductsProductIdRoute
  AuthenticatedStationsStationIdRoute: typeof AuthenticatedStationsStationIdRoute
  AuthenticatedUnitsUidRoute: typeof AuthenticatedUnitsUidRoute
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
  AuthenticatedWorkOrdersWoIdRoute: typeof AuthenticatedWorkOrdersWoIdRoute
  AuthenticatedHmiIndexRoute: typeof AuthenticatedHmiIndexRoute
  AuthenticatedLinesIndexRoute: typeof AuthenticatedLinesIndexRoute
  AuthenticatedOperatorIndexRoute: typeof AuthenticatedOperatorIndexRoute
  AuthenticatedProductionOrdersIndexRoute: typeof AuthenticatedProductionOrdersIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedStationsIndexRoute: typeof AuthenticatedStationsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWorkOrdersIndexRoute: typeof AuthenticatedWorkOrdersIndexRoute
  ApiPublicMesDowntimeRoute: typeof ApiPublicMesDowntimeRoute
  ApiPublicMesKpiRoute: typeof ApiPublicMesKpiRoute
  ApiPublicMesQualityHoldsRoute: typeof ApiPublicMesQualityHoldsRoute
  ApiPublicMesTraceabilityRoute: typeof ApiPublicMesTraceabilityRoute
  ApiPublicMesWorkOrdersRoute: typeof ApiPublicMesWorkOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/waste-reasons': {
      id: '/_authenticated/waste-reasons'
      path: '/waste-reasons'
      fullPath: '/waste-reasons'
      preLoaderRoute: typeof AuthenticatedWasteReasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tracking': {
      id: '/_authenticated/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof AuthenticatedTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/traceability': {
      id: '/_authenticated/traceability'
      path: '/traceability'
      fullPath: '/traceability'
      preLoaderRoute: typeof AuthenticatedTraceabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/telemetry': {
      id: '/_authenticated/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof AuthenticatedTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/step-templates': {
      id: '/_authenticated/step-templates'
      path: '/step-templates'
      fullPath: '/step-templates'
      preLoaderRoute: typeof AuthenticatedStepTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recipes': {
      id: '/_authenticated/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthenticatedRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quality': {
      id: '/_authenticated/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AuthenticatedQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/master-data': {
      id: '/_authenticated/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof AuthenticatedMasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/genealogy': {
      id: '/_authenticated/genealogy'
      path: '/genealogy'
      fullPath: '/genealogy'
      preLoaderRoute: typeof AuthenticatedGenealogyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/execution': {
      id: '/_authenticated/execution'
      path: '/execution'
      fullPath: '/execution'
      preLoaderRoute: typeof AuthenticatedExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/downtime': {
      id: '/_authenticated/downtime'
      path: '/downtime'
      fullPath: '/downtime'
      preLoaderRoute: typeof AuthenticatedDowntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/work-orders/': {
      id: '/_authenticated/work-orders/'
      path: '/work-orders'
      fullPath: '/work-orders/'
      preLoaderRoute: typeof AuthenticatedWorkOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stations/': {
      id: '/_authenticated/stations/'
      path: '/stations'
      fullPath: '/stations/'
      preLoaderRoute: typeof AuthenticatedStationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/production-orders/': {
      id: '/_authenticated/production-orders/'
      path: '/production-orders'
      fullPath: '/production-orders/'
      preLoaderRoute: typeof AuthenticatedProductionOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/operator/': {
      id: '/_authenticated/operator/'
      path: '/operator'
      fullPath: '/operator/'
      preLoaderRoute: typeof AuthenticatedOperatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lines/': {
      id: '/_authenticated/lines/'
      path: '/lines'
      fullPath: '/lines/'
      preLoaderRoute: typeof AuthenticatedLinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hmi/': {
      id: '/_authenticated/hmi/'
      path: '/hmi'
      fullPath: '/hmi/'
      preLoaderRoute: typeof AuthenticatedHmiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/work-orders/$woId': {
      id: '/_authenticated/work-orders/$woId'
      path: '/work-orders/$woId'
      fullPath: '/work-orders/$woId'
      preLoaderRoute: typeof AuthenticatedWorkOrdersWoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/units/$uid': {
      id: '/_authenticated/units/$uid'
      path: '/units/$uid'
      fullPath: '/units/$uid'
      preLoaderRoute: typeof AuthenticatedUnitsUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stations/$stationId': {
      id: '/_authenticated/stations/$stationId'
      path: '/stations/$stationId'
      fullPath: '/stations/$stationId'
      preLoaderRoute: typeof AuthenticatedStationsStationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/products/$productId': {
      id: '/_authenticated/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthenticatedProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/production-orders/$poId': {
      id: '/_authenticated/production-orders/$poId'
      path: '/production-orders/$poId'
      fullPath: '/production-orders/$poId'
      preLoaderRoute: typeof AuthenticatedProductionOrdersPoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/operator/$stationId': {
      id: '/_authenticated/operator/$stationId'
      path: '/operator/$stationId'
      fullPath: '/operator/$stationId'
      preLoaderRoute: typeof AuthenticatedOperatorStationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lines/$lineId': {
      id: '/_authenticated/lines/$lineId'
      path: '/lines/$lineId'
      fullPath: '/lines/$lineId'
      preLoaderRoute: typeof AuthenticatedLinesLineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hmi/$stationId': {
      id: '/_authenticated/hmi/$stationId'
      path: '/hmi/$stationId'
      fullPath: '/hmi/$stationId'
      preLoaderRoute: typeof AuthenticatedHmiStationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/batches/$batchId': {
      id: '/_authenticated/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/batches/$batchId'
      preLoaderRoute: typeof AuthenticatedBatchesBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mes/work-orders': {
      id: '/api/public/mes/work-orders'
      path: '/api/public/mes/work-orders'
      fullPath: '/api/public/mes/work-orders'
      preLoaderRoute: typeof ApiPublicMesWorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mes/traceability': {
      id: '/api/public/mes/traceability'
      path: '/api/public/mes/traceability'
      fullPath: '/api/public/mes/traceability'
      preLoaderRoute: typeof ApiPublicMesTraceabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mes/quality-holds': {
      id: '/api/public/mes/quality-holds'
      path: '/api/public/mes/quality-holds'
      fullPath: '/api/public/mes/quality-holds'
      preLoaderRoute: typeof ApiPublicMesQualityHoldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mes/kpi': {
      id: '/api/public/mes/kpi'
      path: '/api/public/mes/kpi'
      fullPath: '/api/public/mes/kpi'
      preLoaderRoute: typeof ApiPublicMesKpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mes/downtime': {
      id: '/api/public/mes/downtime'
      path: '/api/public/mes/downtime'
      fullPath: '/api/public/mes/downtime'
      preLoaderRoute: typeof ApiPublicMesDowntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDowntimeRoute: AuthenticatedDowntimeRoute,
  AuthenticatedExecutionRoute: AuthenticatedExecutionRoute,
  AuthenticatedGenealogyRoute: AuthenticatedGenealogyRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedMasterDataRoute: AuthenticatedMasterDataRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedQualityRoute: AuthenticatedQualityRoute,
  AuthenticatedRecipesRoute: AuthenticatedRecipesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStepTemplatesRoute: AuthenticatedStepTemplatesRoute,
  AuthenticatedTelemetryRoute: AuthenticatedTelemetryRoute,
  AuthenticatedTraceabilityRoute: AuthenticatedTraceabilityRoute,
  AuthenticatedTrackingRoute: AuthenticatedTrackingRoute,
  AuthenticatedWasteReasonsRoute: AuthenticatedWasteReasonsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBatchesBatchIdRoute: AuthenticatedBatchesBatchIdRoute,
  AuthenticatedHmiStationIdRoute: AuthenticatedHmiStationIdRoute,
  AuthenticatedLinesLineIdRoute: AuthenticatedLinesLineIdRoute,
  AuthenticatedOperatorStationIdRoute: AuthenticatedOperatorStationIdRoute,
  AuthenticatedProductionOrdersPoIdRoute:
    AuthenticatedProductionOrdersPoIdRoute,
  AuthenticatedProductsProductIdRoute: AuthenticatedProductsProductIdRoute,
  AuthenticatedStationsStationIdRoute: AuthenticatedStationsStationIdRoute,
  AuthenticatedUnitsUidRoute: AuthenticatedUnitsUidRoute,
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
  AuthenticatedWorkOrdersWoIdRoute: AuthenticatedWorkOrdersWoIdRoute,
  AuthenticatedHmiIndexRoute: AuthenticatedHmiIndexRoute,
  AuthenticatedLinesIndexRoute: AuthenticatedLinesIndexRoute,
  AuthenticatedOperatorIndexRoute: AuthenticatedOperatorIndexRoute,
  AuthenticatedProductionOrdersIndexRoute:
    AuthenticatedProductionOrdersIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedStationsIndexRoute: AuthenticatedStationsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWorkOrdersIndexRoute: AuthenticatedWorkOrdersIndexRoute,
  ApiPublicMesDowntimeRoute: ApiPublicMesDowntimeRoute,
  ApiPublicMesKpiRoute: ApiPublicMesKpiRoute,
  ApiPublicMesQualityHoldsRoute: ApiPublicMesQualityHoldsRoute,
  ApiPublicMesTraceabilityRoute: ApiPublicMesTraceabilityRoute,
  ApiPublicMesWorkOrdersRoute: ApiPublicMesWorkOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
